
package ukr.astelit.idr.rtn.ws.api.chain;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChainAPI", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChainAPI {


    /**
     * 
     * @return
     *     returns ukr.astelit.idr.rtn.ws.api.chain.ChainsListResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegisteredChainsNames", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "ukr.astelit.idr.rtn.ws.api.chain.GetRegisteredChainsNames")
    @ResponseWrapper(localName = "getRegisteredChainsNamesResponse", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "ukr.astelit.idr.rtn.ws.api.chain.GetRegisteredChainsNamesResponse")
    @Action(input = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/getRegisteredChainsNamesRequest", output = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/getRegisteredChainsNamesResponse")
    public ChainsListResult getRegisteredChainsNames();

    /**
     * 
     * @param chainName
     * @return
     *     returns ukr.astelit.idr.rtn.ws.api.chain.ChainSignatureResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChainSignature", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "ukr.astelit.idr.rtn.ws.api.chain.GetChainSignature")
    @ResponseWrapper(localName = "getChainSignatureResponse", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "ukr.astelit.idr.rtn.ws.api.chain.GetChainSignatureResponse")
    @Action(input = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/getChainSignatureRequest", output = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/getChainSignatureResponse")
    public ChainSignatureResult getChainSignature(
        @WebParam(name = "chainName", targetNamespace = "")
        String chainName);

    /**
     * 
     * @param chainRequest
     * @return
     *     returns ukr.astelit.idr.rtn.ws.api.chain.ChainResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executeChain", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "ukr.astelit.idr.rtn.ws.api.chain.ExecuteChain")
    @ResponseWrapper(localName = "executeChainResponse", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "ukr.astelit.idr.rtn.ws.api.chain.ExecuteChainResponse")
    @Action(input = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/executeChainRequest", output = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/executeChainResponse")
    public ChainResult executeChain(
        @WebParam(name = "chainRequest", targetNamespace = "")
        ChainRequest chainRequest);

    /**
     * 
     * @param chainRequest
     * @return
     *     returns ukr.astelit.idr.rtn.ws.api.chain.ChainResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executeDebugChain", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "ukr.astelit.idr.rtn.ws.api.chain.ExecuteDebugChain")
    @ResponseWrapper(localName = "executeDebugChainResponse", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", className = "ukr.astelit.idr.rtn.ws.api.chain.ExecuteDebugChainResponse")
    @Action(input = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/executeDebugChainRequest", output = "http://chain.api.ws.rtn.idr.astelit.ukr/ChainAPI/executeDebugChainResponse")
    public ChainResult executeDebugChain(
        @WebParam(name = "chainRequest", targetNamespace = "")
        ChainRequest chainRequest);

}
