
package ukr.astelit.idr.rtn.ws.api.chain;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.WebService;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChainAPI", targetNamespace = "http://chain.api.ws.rtn.idr.astelit.ukr/", wsdlLocation = "http://172.16.210.60:8220/idr-rtn/idr-rtn/chain-service?wsdl")
public class ChainAPI_Service
    extends Service
{

    private final static URL CHAINAPI_WSDL_LOCATION;
    private final static WebServiceException CHAINAPI_EXCEPTION;
    private final static QName CHAINAPI_QNAME = new QName("http://chain.api.ws.rtn.idr.astelit.ukr/", "ChainAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.210.60:8220/idr-rtn/idr-rtn/chain-service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHAINAPI_WSDL_LOCATION = url;
        CHAINAPI_EXCEPTION = e;
    }

    public ChainAPI_Service() {
        super(__getWsdlLocation(), CHAINAPI_QNAME);
    }

    public ChainAPI_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHAINAPI_QNAME, features);
    }

    public ChainAPI_Service(URL wsdlLocation) {
        super(wsdlLocation, CHAINAPI_QNAME);
    }

    public ChainAPI_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHAINAPI_QNAME, features);
    }

    public ChainAPI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChainAPI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChainAPI
     */
    @WebEndpoint(name = "ChainAPIPort")
    public ChainAPI getChainAPIPort() {
        return super.getPort(new QName("http://chain.api.ws.rtn.idr.astelit.ukr/", "ChainAPIPort"), ChainAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChainAPI
     */
    @WebEndpoint(name = "ChainAPIPort")
    public ChainAPI getChainAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://chain.api.ws.rtn.idr.astelit.ukr/", "ChainAPIPort"), ChainAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHAINAPI_EXCEPTION!= null) {
            throw CHAINAPI_EXCEPTION;
        }
        return CHAINAPI_WSDL_LOCATION;
    }

}
